### ISSUE TITLE
Mac OSX Ventura 13.5 Firefox 116.0

### ISSUE THREAD

**Issue by Mozart409** [coollabsio/safetyper#2]
Hi,
I bought a “Safetyper - Lifetime License (Earlybird)” version, but nothing happens when I enter my SafeTyper API Key into the add-on. The “Activate” button displays a loading state, but goes back to the original state.

Can you help me?

**Comment by andrasbacsai** [comment]
Hey, it is already reported and I'm working on it. It is related to FF

**Comment by andrasbacsai** [comment]
Could you please check now?

**Comment by Mozart409** [comment]
Thank you it works now.
