### ISSUE TITLE
The Chrome plugin is changing unrelated styles on websites

### ISSUE THREAD

**Issue by mai-soup** [coollabsio/safetyper#4]
Noticed this on https://info.coyotiv.com/, but likely might've also been the case on other sites without me noticing before.

Here is what it looks like with the extension disabled:

![image](https://github.com/coollabsio/safetyper/assets/97809168/863ee1f1-4c36-4872-ae08-f7609a25e512)

And here is what it looks like after toggling the extension back on:

![image](https://github.com/coollabsio/safetyper/assets/97809168/5138da67-126b-4c27-b652-632d42ba5b41)

**Comment by andrasbacsai** [comment]
I completely rewrote it, so this issue does not exist anymore.
